repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.3.1'
    hooks:
    - id: poetry-check
      always_run: true
    - id: poetry-lock
      always_run: true
    - id: poetry-export
      args: ["--without-hashes", "-f", "requirements.txt", "-o", "requirements.txt", "--with", "dev"]
      files: .
      always_run: true
      verbose: true