version: '3.8'

services:
  bot:
    image: telegram-bot
    container_name: telegram-bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "/wait && alembic revision --autogenerate && alembic upgrade head && python main.py"
    ports:
      - 80:8000
    volumes:
      - .:/bot
    environment:
      - WAIT_HOSTS=${RDS_HOSTNAME}:${RDS_PORT}, ${REDIS_HOST}:${REDIS_PORT}, ${RABBITMQ_HOST}:${RABBITMQ_PORT}
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
      - rabbitmq
    networks:
      - local

  celery_worker:
    container_name: telegram-bot-celery-worker
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "celery -A app.celery worker --loglevel=info"
    volumes:
      - .:/bot
    env_file:
      - .env
    depends_on:
      - bot
      - redis
      - rabbitmq
    networks:
      - local

  flower:
    container_name: telegram-bot-flower
    restart: always
    build:
      context: .
    command: >
      bash -c "celery -A app.celery flower --port=5555"
    ports:
      - 5555:5555
    volumes:
      - .:/bot
    environment:
      - CELERY_BROKER_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
      - CELERY_RESULT_BACKEND=redis://${REDIS_HOST}:${REDIS_PORT}/0
    depends_on:
      - celery_worker
      - redis
      - rabbitmq
    networks:
      - local

  mysql:
    image: mysql:8.0
    container_name: telegram-bot-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${RDS_DB_NAME}
      - MYSQL_USER=${RDS_USERNAME}
      - MYSQL_PASSWORD=${RDS_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
    ports:
      - ${EXTERNAL_PORT}:${RDS_PORT}
    volumes:
      - ./app/database/mysql-data:/var/lib/mysql
      - ./app/database/mysql-log:/var/log/mysql
      - ./app/database/mysql-conf:/etc/mysql/conf.d
    env_file:
      - .env
    networks:
      - local

  redis:
    image: redis:latest
    container_name: telegram-bot-redis
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/var/lib/redis
    env_file:
      - .env
    networks:
      - local
    
  redis_commander:
    image: rediscommander/redis-commander:latest
    container_name: telegram-bot-redis-commander
    restart: always
    ports:
      - ${REDIS_COMMANDER_PORT}:${REDIS_COMMANDER_PORT}
    env_file:
      - .env
    environment:
      - REDIS_HOSTS=${REDIS_HOST}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HTTP_USER=${REDIS_COMMANDER_USER}
      - HTTP_PASSWORD=${REDIS_COMMANDER_PASSWORD}
      - PORT=${REDIS_COMMANDER_PORT}
    depends_on:
      - redis
    networks:
      - local


  rabbitmq:
    image: rabbitmq:3-management
    container_name: telegram-bot-rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 1${RABBITMQ_PORT}:1${RABBITMQ_PORT}
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
    env_file:
      - .env
    networks:
      - local

volumes:
  mysql_data:
  mysql_log:
  mysql_conf:
  redis:


networks:
  local:
    driver: bridge
