"""add winners table

Revision ID: 713764557c8e
Revises: dadbbc4db7ff
Create Date: 2023-02-10 23:30:38.537152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '713764557c8e'
down_revision = 'dadbbc4db7ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('winners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_of_victory', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'latest_date_win')
    op.drop_column('users', 'win_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('win_count', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('latest_date_win', mysql.DATETIME(), nullable=True))
    op.drop_table('winners')
    # ### end Alembic commands ###