"""add prize to winners

Revision ID: bf6cef66ec2a
Revises: 713764557c8e
Create Date: 2023-02-10 23:47:34.333924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf6cef66ec2a'
down_revision = '713764557c8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('winners', sa.Column('prize', sa.Float(), nullable=False))
    op.alter_column('winners', 'date_of_victory',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('winners', 'date_of_victory',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('winners', 'prize')
    # ### end Alembic commands ###