version: "3.9"

services:
  alembic:
    image: embassy_bot:latest
    container_name: bot_alembic
    networks:
      - local
    # build:
    #   context: ${PWD}
    #   dockerfile: docker/Dockerfile
    command: /bin/bash -c \
      "echo '[+] Run migrations' && \
      alembic stamp head --purge && \
      alembic revision --autogenerate -m "Migrations" && \
      alembic upgrade head"
    volumes:
      - ${PWD}/:/app
    env_file:
      - ${PWD}/.env
    depends_on:
      database:
        condition: service_healthy
