version: "3.9"

services:
  celery_worker:
    # properties
    image: telegram_bot:latest
    container_name: tg_bot_celery_worker

    # settings
    restart: unless-stopped

    # commands
    command: >
      bash -c "celery -A app.celery:celery_app worker -B --loglevel=info"

    # dependencies
    env_file:
      - ${PWD}/.env
    depends_on:
      - redis

    # attachments
    volumes:
      - ${PWD}:/app
    networks:
      - local

  # celery_beat:
  #   # properties
  #   image: embassy_bot:latest
  #   container_name: bot_celery_beat

  #   # settings
  #   restart: unless-stopped

  #   # commands
  #   command: >
  #     bash -c "celery -A app.celery:celery_app beat --loglevel=info"

  #   # dependencies
  #   env_file:
  #     - ${PWD}/.env
  #   depends_on:
  #     - redis

  #   # attachments
  #   volumes:
  #     - ${PWD}:/app
  #   networks:
  #     - local

  # flower:
  #   # properties
  #   image: embassy_bot:latest
  #   container_name: bot_flower

  #   # settings
  #   restart: unless-stopped
  #   ports:
  #     - 5555:5555

  #   # commands
  #   command: >
  #     bash -c "celery -A app.celery flower --port=5555"

  #   # dependencies
  #   environment:
  #     - CELERY_BROKER_URL=redis://${REDIS_HOST}:${REDIS_PORT}/0
  #     - CELERY_RESULT_BACKEND=redis://${REDIS_HOST}:${REDIS_PORT}/1
  #   env_file:
  #     - ${PWD}/.env
  #   depends_on:
  #     - celery_worker
  #     - redis

  #   # attachments
  #   networks:
  #     - local
