version: "3.9"

services:
  celery_worker:
    container_name: bot_celery_worker
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "celery -A app.celery worker --loglevel=info"
    volumes:
      - .:/bot
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
    networks:
      - local

  flower:
    container_name: bot_flower
    restart: unless-stopped
    build:
      context: .
    command: >
      bash -c "celery -A app.celery flower --port=5555"
    ports:
      - 5555:5555
    volumes:
      - .:/bot
    environment:
      - CELERY_BROKER_URL=redis://${REDIS_HOST}:${REDIS_PORT}/0
      - CELERY_RESULT_BACKEND=redis://${REDIS_HOST}:${REDIS_PORT}/1
    depends_on:
      - celery_worker
      - redis
      - rabbitmq
    networks:
      - local
