version: "3.9"

services:
  database:
    image: postgres:latest
    container_name: bot_database
    networks:
      - local
    volumes:
      - postgres_data_database:/var/lib/postgresql/data/
    env_file:
      - ${PWD}/.env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT_EXPOSE}:5432
    expose:
      - ${DATABASE_PORT_EXPOSE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    command: -p 5432

volumes:
  postgres_data_database:
