version: "3.9"

services:
  database:
    # properties
    image: postgres:latest
    container_name: tg_bot_database
    
    # settings
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT_EXPOSE}:5432

    # commands
    command: -p 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

    # dependencies
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file:
      - ${PWD}/.env

    #attachments
    volumes:
      - postgres_data_database:/var/lib/postgresql/data/
    networks:
      - local
