services:
  redis:
    # properties
    image: redis:latest
    container_name: tg_bot_redis

    # settings
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379

    # commands
    command: redis-server --save 20 1 --loglevel warning

    # dependencies
    env_file:
      - ${PWD}/.env

    # attachments
    volumes:
      - redis:/var/lib/redis
    networks:
      - local
